### ISSUE TITLE
Pandas error with dataframe append() function

### ISSUE THREAD

**Issue by srcrowl** [louadi/NEASE#11]
When running NEASE with newest version of pandas, get error due to the fact that append() function is no longer present in the new pandas. This occurs after some results have already been printed out. It would be nice to either explicitly mention that a lower pandas version is required or update code for new pandas. Unless there is a fix that I am missing. Thanks!

Traceback
{
	"name": "AttributeError",
	"message": "'DataFrame' object has no attribute 'append'",
	"stack": "---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\\AppData\\Local\\Temp\\ipykernel_33804\\2553761319.py in ?()
----> 1 events = nease.run(data_for_nease, organism = 'Human')

\\Lib\\site-packages\nease\nease.py in ?(self, data, organism, input_type, p_value_cutoff, remove_non_in_frame, only_divisible_by_3, min_delta, Majiq_confidence, only_DDIs)
    227 
    228                 # Identify binding of affected domains = Edges in the PPI
    229                 # get DMI adn DDI for spliced domains
    230 
--> 231                 self.interacting_domains=affected_edges(self,Join,self.only_DDIs)
    232 
    233 
    234 

\\Lib\\site-packages\nease\\functions.py in ?(nease_data, Join, only_DDIs)
    117 
    118 
    119 
    120 
--> 121                     interacting_domains=interacting_domains[['Gene name','NCBI gene ID','Identifier','dPSI','Affected binding (NCBI)']].append(elm_affected, ignore_index=True)
    122 
    123 
    124 

\\Lib\\site-packages\\pandas\\core\\generic.py in ?(self, name)
   5985             and name not in self._accessors
   5986             and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987         ):
   5988             return self[name]
-> 5989         return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'"
}

**Comment by louadi** [comment]
Hi,

This issue was fixed in https://github.com/louadi/NEASE/pull/10.

Could you please try to re-install NEASE and try again? 

Best,
Zakaria

**Comment by louadi** [comment]
fixed.
