### ISSUE TITLE
Extracting Which Changes Disrupt the ORF

### ISSUE THREAD

**Issue by astarr97** [louadi/NEASE#6]
Hello again,

I am wondering if there is a way to extract which splicing events are predicted to disrupt the ORF/lead to NMD.  I have looked through the source code and there doesn't seem to be an easy way to do so. 

Best, Alex.

**Comment by louadi** [comment]
Hi Alex,

I think the easiest way would be to use [this reference ](https://vastdb.crg.eu/wiki/Downloads). Have a look at the protein impact file, and look if your list of events overlaps with some of them.

Best,
Zakaria

**Comment by astarr97** [comment]
Thanks!
