### ISSUE TITLE
Request for including Mouse db

### ISSUE THREAD

**Issue by shregeno8** [louadi/NEASE#8]
Hi
I was wondering whether you would be able to add Mouse database into this tool or is there a way I could manually do it?

Will be much appreciated.

Thanks

**Comment by louadi** [comment]
Hi, 

Unfortunately, the current version only supports human dataset. If you would like to add mouse data yourself have a look at the data folder in the package and try to process it similarly. If you have any questions I m happy to answer them.

Sorry for the not very positive answer..

Best,
Zakaria

**Comment by louadi** [comment]
NEASE now supports mouse data (https://github.com/louadi/NEASE/commit/99a311ba4cc8b6cf3bd59a548221c05f2d27dd57).
