### ISSUE TITLE
Using HALLMARK Ontology

### ISSUE THREAD

**Issue by hust-yyan** [louadi/NEASE#9]
Hello,

I have been using NEASE and had a quick question. I am wondering whether it is possible to use additional ontologies such as the MSigdb Hallmark. If yes, do some suggestions on how I could do that?

Meanwhile, I noticed that currently NEASE can only handle SE type events for rmats input, right?

**Comment by louadi** [comment]
Hi there,

Thanks for using NEASE!

You are correct but for other splice events, you could try to prepare them as standard input where the start and the end of the sequence are the difference between the two exons. Like the additional not added from a 3 'splice site. This will be mapped to the Domain region in the same way. 

For intron retention using the classical approach would make more sense. 

We are working on extending NEASE to include more species and datasets, but unfortunately for now including custom ontologies is not supported. I'm sorry for the inconvenience, I'll update you if we release a new version.

Best,
Zakaria
